name: Fetch YouTube data and update youtube.json

on:
  schedule:
    - cron: '*/15 * * * *'  # 15分ごとに実行（UTC）
    #- cron: '0 * * * *'  # 毎時0分に実行（UTC）
  workflow_dispatch:         # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetch_youtube.js
        run: node fetch_youtube.js
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Commit and push youtube data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          # 変更されたJSONをステージ
          git add data/youtube.json data/youtube_cache.json || true
      
          # 何もステージされてなければスキップ
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update youtube data"
            git push
          fi

